### ISSUE TITLE
Please make a release for adding e2mmap as explicit dependency

### ISSUE THREAD

**Issue by johannesluedke** [ruby/thwait#3]
Since Ruby 2.7.0, one needs to additionally manually put `e2mmap` in Gemfile. It looks like this is already fixed with https://github.com/ruby/thwait/pull/2. 
Can you plase also make a release from this, so that a bundle update would resolve needing to require e2mmap?

**Comment by hsbt** [comment]
Just released https://rubygems.org/gems/thwait/versions/0.2.0 with its fixes.
